version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 928359770130.dkr.ecr.us-east-1.amazonaws.com
      - cd analytics
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t analytics:latest .
      - docker tag analytics:latest 928359770130.dkr.ecr.us-east-1.amazonaws.com/analytics:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 928359770130.dkr.ecr.us-east-1.amazonaws.com/analytics:latest