apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
  labels:
    app: analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
        - name: analytics
          image: 928359770130.dkr.ecr.us-east-1.amazonaws.com/analytics:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
          # env:
          #   - name: DB_PASSWORD
          #     valueFrom:
          #       secretKeyRef:
          #         name: postgresql
          #         key: postgres-password
          ports:
            - containerPort: 5000
