apiVersion: v1
kind: Service
metadata:
  name: analytics
  labels:
    app: analytics
spec:
  type: LoadBalancer
  selector:
    app: analytics
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
