apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-storage
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 256Mi
  selector:
    matchLabels:
      name: models-1-0-0